steps:

  integrationArtifactUpload:
      cpiApiServiceKeyCredentialsId: san_apikey1
      integrationFlowId: new_flow
      integrationFlowName: San_QA_Flow
      packageId: TestIflow
      filePath: ./iflows/new_flow.zip
  
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: san_apikey1
    integrationFlowId: new_flow
 
  integrationArtifactUnDeploy:
    cpiApiServiceKeyCredentialsId: cpiapi
    integrationFlowId: new_flow
