steps:
integrationArtifactDownload:
     cpiApiServiceKeyCredentialsId: CPIAPI
    integrationFlowId: new_flow
    integrationFlowVersion: 1.0.4
    downloadPath: ./iflows

  integrationArtifactUpload:
      cpiApiServiceKeyCredentialsId: san_apikey1
      integrationFlowId: new_flow
      integrationFlowName: San_QA_Flow
      packageId: TestIflow
      filePath: ./iflows/new_flow.zip
  
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: san_apikey1
    integrationFlowId: new_flow
 
  integrationArtifactUnDeploy:
    cpiApiServiceKeyCredentialsId: cpiapi
    integrationFlowId: new_flow
